### ISSUE TITLE
Allow GIL to be released with threads=1

### ISSUE THREAD

**Issue by hgomersall** [hgomersall/pyFFTW#13]
Currently the GIL is never released during executions if the FFTW object is single threaded. In a Python multithreaded environment, it may be helpful to execute FFTW objects in parallel in different Python threads so there should be a way for the user to turn off the GIL even when the number of threads used by the FFTW object is 1.

**Comment by r-atwood** [comment]
Hi, 
is this an issue for the following use, many instances of the same FFT being called on each of a 
large number of identical arrays. The routine uses the multiprocessing module . Abbreviated code is below. 

In this use, I have two questions that seem to be related to this issue , 

1. Does this suffer from not ulocking the GIL as mentioned, thus it should be faster than it is? It seems faster than using one single thread already. 

2. Is it threadsafe against multiple threads modifying the array being processed in fft_object? I thought that fftw used the exact array that was designated at "planning" time ? Or is it always using an array of identical type but in a different memory location? 

Thanks 
Robert

____________________________________________________
import pyfftw
import multiprocessing.

**** In main routine ***  

fft_object = pyfftw.FFTW(a, b, axes=(0,1))
ifft_object = pyfftw.FFTW(c, d, axes=(0,1), direction='FFTW_BACKWARD')


for i in range(n):
     p = multiprocessing.Process(target=ravenfilter,args=((..blah..blah.., fft_object,ifft_object)))
     jobs.append(p)
     p.start()

**** In a function****
def ravenfilter( ... several args... , fft_object,ifft_object):
     ... get the array 'sinogram' somehow ... 
      sino2=ft_object(sinogram)
     ... more operations ..

**Comment by hgomersall** [comment]
1) Lots of calls to identical arrays should not really be affected by the GIL issue unless you're running stuff in multiple threads yourself. Multiprocessing uses different processes anyway so shouldn't really be affected either way.

It's perfectly plausible that many small transforms are faster in a single thread in which the threading overhead is greater than any speed up. As always, try it and see :)

2) If multiple threads hit the same array, you should expect things to break. The idea is that other threads might be doing other things (or running other FFTW instances or whatever) and so the GIL can be released whilst FFTW is working.

Does that answer the qs?

**Comment by r-atwood** [comment]
Thanks for the speedy reply.
I am afraid it may answer the question by referring to things I am not familiar enough with, in Python. 
If you can clarify a couple of things about your answer it would be very helpful. 
'unless you're running stuff in multiple threads yourself' -- I am not sure , technically speaking, what constitutes 'running it yourself' . In this case the function launched by Process simplly filters in Fourier space i.e. does  a forward transform, some arithmetic, then a reverse transform. At present it also inputs and outputs from/to the disk. It is only accessed through multiprocessing. Process and no other threading library or operations are used in this Python script. Is that what you mean, if I used other threading outside multiprocessing.Process module? Is the 'multiprocessing' module not actually using threads? 

I think your answer means that there is not a problem in this case? 


 My worry is about whether fft_object contains pointers to the original array used in planning (a and/or b) and whether this array is used during the call to the object. The object fft_object is passed to the thread function, but, technically, I don't really understand  whether that's a copy or a reference, nor whether the object does use this original array or not. In C-fftw, i was under the impression that it did and that one must 'plan' with the exact array that one performs the transform, but perhaps for more advanced users  it is sufficient to use an identically type and layout array in a different location in memory, and this is what pyFFTW does? 


Thanks again
Robert

**Comment by hgomersall** [comment]
No, multiprocessing is not using threads at all, but separate processes (this is how it can sidestep the GIL issue). I suspect in you case there is no problem; if you're not explicitly using threads, I doubt there are any being used.

I don't quite follow your last paragraph. Everything in python is by reference unless a copy is made explicitly - really "variables" are just references to some object or other. Do you mean in the context of multiprocessing? I'm actually not sure what happens here. You may be avoiding any problem by updating the memory when you call it (by passing a new input array). I honestly don't know... I think it must be copying, but I don't know how this interacts with FFTW. Does it work?

**Comment by hgomersall** [comment]
Fixed with 0fed0706aaa6898913d4e8716d7eb3f9a4a1351d.
