### ISSUE TITLE
pyfftw vs numpy.fft: faster and slower

### ISSUE THREAD

**Issue by francispoulin** [hgomersall/pyFFTW#58]
Hello,

I am learning how to use pyfftw in hopes of speeding up my codes.

I am doing a simple comparison of pyfftw vs numpy.fft for a variety of resolutions.

On my ubuntu machine, when the grid is large enough, I get an improvement by a factor of 3.  I think this it to be expected since I read somewhere that fftw is about 3 times faster than fftpack, what numpy and scipy use.  This is the good news.

I also tried it on my mac that is using Anaconda.  Very simple to install, but maybe some problems.  When I run the same code pyfftw it runs marginally slower.

I tried to print the version of each but it didn't seem to recognize that.  I presume they are using the same version but I don't know.

Any ideas what might be the problem or how I can speed it up?

Unfortunately, my built in version of python on my mac has problems installing pyfftw, as well as other issues so I'd like to avoid that if at all possible.

Best regards,
Francis

**Comment by hgomersall** [comment]
Can you post your test code?

**Comment by francispoulin** [comment]
Sorry that I didn't post this before.

The code that someone wrote can be found at the following location. I believe the author based this on what is done in spectralDNS, which is done efficiently.

https://github.com/Poulin-Research-Group/fftw-tests

Sorry for the bother but thanks in advance for your help.

**Comment by hgomersall** [comment]
Hmmm the code looks pretty sensible. I've no idea to be honest. Did you compile FFTW yourself?

**Comment by francispoulin** [comment]
I have at some point in time but I have several versions lying around.  I am not sure which anaconda is using.  I presume it would use it's own but I don't know.  

Is there a safe way you might recommend of installing fftw or pointing pyfftw to a particular library?

**Comment by hgomersall** [comment]
I mean, is the FFTW you are testing one you compiled yourself? It can be non-trivial I think to get all the optimisations working properly. The current suggested strategy is to use homebrew. You'll need a few compiler flags setup, which can be done as described in the readme on the [front page](https://github.com/hgomersall/pyFFTW). If you've already done something similar, I'm at a bit of a loss.

**Comment by hgomersall** [comment]
Are you instally pyfftw from git or from pypi?

**Comment by francispoulin** [comment]
I am reinstalling my installation with fink (should be as good as homebrew, maybe?), to see if that helps.

I used pip.  But I can try using git if you think that would help.

**Comment by francispoulin** [comment]
I installed fftw and fftw3 using fink and that seemed to work.

I removed pyfftw and reinstalled it, and I was told it was successful.

This is where things get strange.

After installing it I ran python from anaconda, it said it was 2.7.8, and I was able to import pyfftw.

When I tried it in another window, I open up python anaconda and it is 2.7.9 and it won't import pyfftw.  I get the error below.  

I can't seem to find traces of the 2.7.8 where pyfftw could be imported but do you have any suggestions how I can diagnose this problem?
 
>>> import pyfftw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/anaconda/lib/python2.7/site-packages/pyfftw/__init__.py", line 16, in <module>
    from .pyfftw import (
ImportError: dlopen(/Applications/anaconda/lib/python2.7/site-packages/pyfftw/pyfftw.so, 2): Library not loaded: libfftw3.3.dylib
  Referenced from: /Applications/anaconda/lib/python2.7/site-packages/pyfftw/pyfftw.so
  Reason: image not found

**Comment by hgomersall** [comment]
It sounds like you have two installations of python. I'm really clueless about Apple Macs. I used one once for about 10 minutes once and I got frustrated with the keyboard layout.

Perhaps begin again? Uninstall everything? Presumably when you installed pyfftw, you ran python? pyfftw should be installed with that version of python. Is there something in the environment path which selects which version is being used? Does anaconda fiddle with this?

It might be worth asking about this specific point (multiple python versions) on StackOverflow...

**Comment by hgomersall** [comment]
Oh, I noticed you had a problem with the lib being found. hmm I don't know. Are the various environment settings you configured correct?

**Comment by francispoulin** [comment]
By environment variables, you mean the PATH and the library. I think so.

Below you can see that the library is in the right location and the paths are what I thought what they should be set to be.  Did I miss something?

am-laptop24:~ fpoulin$ ls /sw/lib/libfftw3.3.dylib 
/sw/lib/libfftw3.3.dylib
am-laptop24:~ fpoulin$ echo echo $DYLD_LIBRARY_PATH
echo sw/lib
am-laptop24:~ fpoulin$ echo $LDFLAGS
-L/sw/include
am-laptop24:~ fpoulin$ echo $CFLAGS
-I/sw/include

**Comment by hgomersall** [comment]
Your path DYLD_LIBRARY_PATH is relative, is that the problem? I think it should be `/sw/lib` (not `sw/lib`).

**Comment by francispoulin** [comment]
Very, very sorry about my dumb typo.

Yes, that did the trick. And now it is running, on the order of 3 times faster!

Thanks for your patience and sorry for my silly mistake.

**Comment by hgomersall** [comment]
:) I'm pleased it is sorted
