### ISSUE TITLE
No exception on wrong arguments of function call of pyfftw.FFTW(...)

### ISSUE THREAD

**Issue by hyliu1989** [hgomersall/pyFFTW#60]
When I call this function with wrong parameter 'thread', the exception or error does not raise. 

Here is the executed result. I added a random string in my code so that the programme stops at that string. The wrong argument is the 'thread' in line 129, which should be 'threads'.

"""""""""""" start of the executed result from IPython """"""""""""
/xxx/xxx/xxx.py in \<module\>()
    129 ifftObj2 = pyfftw.FFTW(f_buffer2, x_buffer2,  axes=(-2,-1), direction='FFTW_BACKWARD', flags=flags, thread=n_cpu)
    130 
--> 131 adfasf
    132 def SquareSelection(outplane, inplane, iXBeg, iXEnd, iYBeg, iYEnd):
    133     diffXSign = iXBeg < 0 and iXEnd >= 0

NameError: name 'adfasf' is not defined
""""""""""""" end of the executed result from IPython """""""""""""

**Comment by hyliu1989** [comment]
I am not familiar with cylone, but I guess taking out *args and *kw in line 1100 pyfftw.pyx would do the job.

**Comment by hgomersall** [comment]
Apologies I didn't clock this issue sooner. Can you post just what you are calling?

**Comment by hgomersall** [comment]
This is interesting. I've no idea why I did add *args and **kwargs - probably a legacy of some very early code that sneaked through.

**Comment by hyliu1989** [comment]
Below is what I called:
pyfftw.FFTW(f_buffer2, x_buffer2, axes=(-2,-1), direction='FFTW_BACKWARD', flags=flags, thread=n_cpu)

Note that there is a "thread" instead of the desired "threads".
Hope that this helps improve the project :)

**Comment by hgomersall** [comment]
This is now fixed in 286f62f7f8f4ca2f68cba11e7ccde85907015be4. Thanks for that!

**Comment by hgomersall** [comment]
Just a quick FYI, `__cinit__` requires the *args and **kwargs to allow for inheritance. It should have been, and now is, picked up by `__init__`.
