### ISSUE TITLE
Striding in n_byte_align not on a uniform standard

### ISSUE THREAD

**Issue by robbmcleod** [hgomersall/pyFFTW#61]
Howdy, I've been using the FFTW object interface to accelerate a cross-correlation routine.  Prior to taking the FFT I rotate some of the images by 90 degrees. However, numpy doesn't do this physically, it just changes the striding of the array, which is of little use for pyFFTW.  Then when I try to use n_byte_align() to restore the striding, it doesn't enforce to the same striding format as n_byte_align_empty().

     fixedImageFFT = pyfftw.n_byte_align_empty( shapeOptimized, fftwdtype.itemsize, dtype=fftwdtype )
    # Striding of images is ( 16384, 8 )
    temp = np.rot90( images[I,:,:], k=-1 )
    # Striding of temp is ( 8, -16384 )
    fixedImage = np.copy( temp )
    # Striding of fixedImage is ( 8, 16394 )
    fixedImage = pyfftw.n_byte_align( temp, fftwdtype.itemsize, dtype=fftwdtype )
    # Striding of fixedImage is unchanged ( 8, 16394 ), update_arrays pops an error
    fixedFFT2.update_arrays( fixedImage, fixedImageFFT ); fixedFFT2.execute()

The solution I found was to use stride_tricks in place of n_byte_align:

    fixedMask = np.lib.stride_tricks.as_strided( np.copy(temp), fixedMaskFFT.shape, fixedMaskFFT.strides )
    # Striding is now ( 16384, 8 )
    fixedFFT2.update_arrays( fixedImage, fixedImageFFT ); fixedFFT2.execute()
    # Done

My feeling is that n_byte_align() needs to enforce uniform striding that is compatible with n_byte_align_empty().

**Comment by robbmcleod** [comment]
Anyone point that I should raise: as_strided blows up on the FFTW.execute() call if you do it in-place.

i.e.
    fixedImage = np.copy(temp)
     fixedImage = np.lib.stride_tricks.as_strided( fixedImage, fixedMaskFFT.shape, fixedMaskFFT.strides )
    # Striding is now ( 16384, 8 )
    fixedFFT2.update_arrays( fixedImage, fixedImageFFT )
    fixedFFT2.execute() # crashes

Causes the Python interpreter to crash without an error message inside the fftw library. I don't have debug versions of FFTW (assuming such a thing exists) so I don't know anything more about it.

**Comment by hgomersall** [comment]
Ok, this is interesting (and apparently serious!). Can you post a [minimum (not) working example](http://yoda.arachsys.com/csharp/complete.html) for this...

**Comment by robbmcleod** [comment]
Hi Henry,

I asked the question on StackOverflow and was given good answers:

http://stackoverflow.com/questions/29699888/force-numpy-array-to-physically-match-striding-in-memory

Here's a code fragment:

    import numpy as np
    import pyfftw
    
    N = 512
    xmesh, ymesh = np.meshgrid( np.arange(-N/2,N/2), np.arange(-N/2,N/2))
    mage = np.exp( -(xmesh/256.0)**2.0 - (ymesh/64.0)**2.0 ).astype( 'complex64' )
    print( "Starting image: " + str(mage.strides) )
    rotmage = np.rot90( mage )
    print( "Rotated" + str(rotmage.strides) )
    mage[:] = np.rot90( mage )
    print( "Rotated force update in-place: " + str(mage.strides) )
    nbyte_rotmage = pyfftw.n_byte_align( rotmage, 8, dtype='complex64' )
    print( "N-byte ordered: " + str(nbyte_rotmage.strides) )
    copy_rotmage = np.copy( rotmage )
    print( "Default copy: " + str(copy_rotmage.strides) )
    copyc_rotmage = np.copy( rotmage, order='C')
    print( "C-ordered copy: " + str(copyc_rotmage.strides)  )

So the short answer is, the coder either must force the update in place with [:]  or use the np.copy( A, order='C' )  option.  I  tried looking at the cython files to see what n_byte_align() does but it appears to have been removed?

**Comment by hgomersall** [comment]
It's in [utils.pxi](https://github.com/hgomersall/pyFFTW/blob/master/pyfftw/utils.pxi). Bear with me, I'm travelling at the moment, but I'll try to get something sensible quickly...

**Comment by hgomersall** [comment]
Yes, it was the crash I was most worried about! It should _never_ crash - no problems getting an exception, but a crash is a failure. Please show me how to duplicate it.

**Comment by robbmcleod** [comment]
Hi, sorry but upon further investigation it seems the problem is in numpy with numpy.lib.stride_tricks.as_strided() but there is a delay between calling this function and the interpreter crash.  It looks like there's about 20 ms in-between calling this function and the interpreter crashing, which made it look like it was happening inside pyFFTW.FFTW.execute(), as this just happened to be the last executed line.

I'll report it to the Continuum people I guess.  

For your interest, here is the code with pyFFTW completely commented-out (still crashes):

    import numpy as np
    # import pyfftw
    from time import time
    
    N = 512
    xmesh, ymesh = np.meshgrid( np.arange(-N/2,N/2), np.arange(-N/2,N/2))
    fftwdtype = np.dtype( 'complex64' )

    mage = np.exp( -(xmesh/256.0)**2.0 - (ymesh/64.0)**2.0 ).astype( fftwdtype )
    print( "Starting image striding: " + str(mage.strides) )
    rotmage = np.rot90( mage )
    print( "Rotated image striding : " + str(rotmage.strides) )
    copy_rotmage = np.copy( rotmage, order='K' )
    print( "Default copied rotated image striding : " + str(copy_rotmage.strides) )
    
    # mageFFT = pyfftw.n_byte_align_empty( mage.shape, fftwdtype.itemsize, dtype=fftwdtype )
    t0 = time()
    restrided_rotmage = np.lib.stride_tricks.as_strided( rotmage, shape=mage.shape, strides=mage.strides )

    print( "Re-strided rotated image striding : " + str(restrided_rotmage.strides) )
    # print( "Image FFT striding : " + str(mageFFT.strides) )

    # Python executes code
    # FFT2 = pyfftw.builders.fft2( mage )
    # FFT2.update_arrays( restrided_rotmage, mageFFT )
    # FFT2.execute()
    
    # Let's try and time how long it takes to crash
    for J in np.arange(0,10E3):
        print( "Still processing : " + str(time()-t0) )
        pass

I'll close the bug.

**Comment by hgomersall** [comment]
Thanks Rob. Please feel free to leave any more bugs that appear! Zero bugs is the goal :)
