### ISSUE TITLE
build with mingw

### ISSUE THREAD

**Issue by arve0** [hgomersall/pyFFTW#62]
I'm unable to build on windows with mingw. Environment is 32bit python 3.4.3 from conda. Distutils build is set to mingw.

Here is the bottom of the error message:
```
c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw.o:pyfftw.c:(.text+0x1a520): und
efined reference to `_imp___Py_FalseStruct'
c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw.o:pyfftw.c:(.text+0x1a52d): und
efined reference to `_imp___Py_NoneStruct'
c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw.o:pyfftw.c:(.text+0x1a762): und
efined reference to `_imp__PyMethod_Type'
c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw.o:pyfftw.c:(.text+0x1c39c): und
efined reference to `_imp__PyExc_ImportError'
c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw.o:pyfftw.c:(.text+0x1c4b2): und
efined reference to `_imp___Py_NoneStruct'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: c:\users\t
cs-user\downloads\pyfftw\pyfftw\pyfftw.o: bad reloc address 0x0 in section `.dat
a'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1
```

[This stackoverflow question](http://stackoverflow.com/questions/27389530/bad-reloc-address-0x0-in-section-data-c-extensions-for-python) suggest that the library needs to be linked.

**Comment by arve0** [comment]
This is the command that fails:
```
C:\MinGW\bin\gcc.exe -shared -s c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw
.o c:\users\tcs-user\downloads\pyfftw\pyfftw\pyfftw.def -LC:\Users\TCS-User\Down
loads\pyFFTW\pyfftw -LC:\Users\TCS-User\Miniconda32\libs -LC:\Users\TCS-User\Min
iconda32\PCbuild -llibfftw3-3 -llibfftw3f-3 -llibfftw3l-3 -lpython34 -lmsvcr100
-o build\lib.win32-3.4\pyfftw\pyfftw.pyd
```

**Comment by hgomersall** [comment]
uhm... I've no idea - the cython stuff should be handled automagically. Windows is a complete ball ache to get working. Do you need to build it yourself?

You can always try grabbing these, which seem to be a more recent version than the pip release:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyfftw

**Comment by arve0** [comment]
No, I do not need to build it. Just tried since pypi did not contain a
release for Python 3.4. I'll try the gohlke- build.

**Comment by hgomersall** [comment]
great, let me know if it works.

**Comment by arve0** [comment]
Just needed a :coffee:-break - this windows installing is destroying me. gohlke's build **works**! :smile:

**Comment by hgomersall** [comment]
whoop! I'll push 3.4 versions when I make the release (which is being stalled by my total reluctance to boot into windows).

**Comment by hgomersall** [comment]
Oh, I just came across this:
https://github.com/cython/cython/wiki/InstallingOnWindows
under "Troubleshooting", the first described issue looks suspiciously like yours. I'll be curious to know if that fixes it?

**Comment by arve0** [comment]
- installed pexports via mingw-get
- found python34.dll in miniconda directory
- `pexports python34.dll > python34.def`
- `dlltool --dllname python34.dll --def python34.def --output-lib libpython34.a`
- python setyp.py install
- same error

**Comment by hgomersall** [comment]
Did you copy the results as well? Anyway, it doesn't really matter. It's pain to get working I know, so don't waste too much time on it.

**Comment by arve0** [comment]
Yey! :tada: `cp Miniconda32/libpython34.a Miniconda32/python34.def Downloads/pyFFTW/pyFFTW` did the trick.
