### ISSUE TITLE
Merging/sharing wisdom

### ISSUE THREAD

**Issue by smallnamespace** [hgomersall/pyFFTW#72]
Is there a safe way to merge wisdom from multiple instances of pyFFTW?

Right now I have a setup where wisdom is written to a user location and periodically updated, but if I run multiple instances of my application simultaneously, then we only randomly accumulate wisdom from one instance upon every write.

Would a naive merge (e.g. treating the wisdom tuple/string as a nested dictionary and merging along the hierarchical keys) work?

If so, mind if I add a merge_wisdom or update_wisdom call to the library?

**Comment by hgomersall** [comment]
The wisdom is just a tuple of strings that is dumped by FFTW (one entry in the tuple for each of float, double and long double). There is no problem with sharing wisdom through an intermediate file: each instance doing an atomic open, read, write back or similar.

The existing import_wisdom _is_ a merge wisdom - it's doesn't forget what it already knows (take a look at what is exported when some stuff is imported).

**Comment by smallnamespace** [comment]
Ok, so it sounds like to write a merged wisdom, all I need to do is to load the wisdom file before saving to it again (all atomically)? I'll give it a try.
