### ISSUE TITLE
Installing pyfftw on Anaconda3 on Windows 7

### ISSUE THREAD

**Issue by hyliu1989** [hgomersall/pyFFTW#73]
Hi, I recently underwent a painful process of installing pyfftw on Anaconda3 and want to share the steps in order to avoid people undergoing the same thing. Assuming that a user has Python 3.5 installed through Anaconda3. Here are the steps:
1.  Install "Visual Studio Express 2013 for Desktop". (newer version does not work since the newer does not have io.h, etc.)
2.  Download the FFTW for Windows from http://www.fftw.org/install/windows.html
3.  Extract the zipped file and put the following files into Anaconda3\libs (not Anaconda3\lib):
    libfftw3-3.dll,  libfftw3f-3.dll,    libfftw3l-3.dll,
    libfftw3-3.def,  libfftw3f-3.def,    libfftw3l-3.def
4.  Open "VS2013 x64 Cross Tools Command Prompt" from the startup menu, and cd to Anaconda3\libs
5.  Run the following commands:
        lib /def:libfftw3-3.def /MACHINE:X64
        lib /def:libfftw3f-3.def /MACHINE:X64
        lib /def:libfftw3l-3.def /MACHINE:X64
    Until now, the FFTW should be correctly install for pip
6.  Run "pip install pyfftw". If there are __imp_* symbol problems, run step 5 again and then run step 6.
7.  move the following files to Anaconda3\Lib\site-packages\pyfftw
        libfftw3-3.dll,  libfftw3f-3.dll,    libfftw3l-3.dll
8. Happy using Pyfftw!

[After notes] The main problem is that pip install does not recognise many things (like some VC headers, FFTW libraries), and I don't know why. The above steps are rather lengthy but it works well and is tested many times (thanks to multiple machines I am using). I hope this post can somehow help.

**Comment by hgomersall** [comment]
Thanks for that info.

The current appveyor build  (in the appveyor branch) is set up to generate suitable builds for all windows versions and test them. It just tests at the moment, but hopefully this week I'll get round to having them pushed up somewhere on build success.

That means there should always be the latest release as well as the current head available as a windows download.

**Comment by hgomersall** [comment]
Just to follow this up, development builds are now being pushed automatically to bintray after successful test completion:
https://bintray.com/hgomersall/generic/PyFFTW-development-builds/view#

They're built using miniconda and against numpy 1.9, so they should work fine in your case.

**Comment by hannahbarta** [comment]
Would a similar process work for Python 2.7?

**Comment by billinair** [comment]
Follow this process, everything works fine until 'pip install pyfftw'. I always get this error:

Failed to build pyfftw 
......
ValueError: path '/home/whg/Projects/github/pyFFTW/pyfftw/pyfftw.c' cannot be absolute

I am using Anaconda 3.5. Windows 10 _ 64bits. Visual Studio 2017.
Visual studio 2013 only has 32bit version?

**Comment by zfphil** [comment]
I got around this by installing an older version:

`pip install pyfftw==0.9.2`

**Comment by saharsalimpour** [comment]
When I run "lib /def:libfftw3-3.def /MACHINE:X64
" I get this error: 'lib' is not recognized as an internal or external command,

**Comment by saharsalimpour** [comment]
> Hi, I recently underwent a painful process of installing pyfftw on Anaconda3 and want to share the steps in order to avoid people undergoing the same thing. Assuming that a user has Python 3.5 installed through Anaconda3. Here are the steps:
> 
> 1. Install "Visual Studio Express 2013 for Desktop". (newer version does not work since the newer does not have io.h, etc.)
> 2. Download the FFTW for Windows from http://www.fftw.org/install/windows.html
> 3. Extract the zipped file and put the following files into Anaconda3\libs (not Anaconda3\lib):
>    libfftw3-3.dll,  libfftw3f-3.dll,    libfftw3l-3.dll,
>    libfftw3-3.def,  libfftw3f-3.def,    libfftw3l-3.def
> 4. Open "VS2013 x64 Cross Tools Command Prompt" from the startup menu, and cd to Anaconda3\libs
> 5. Run the following commands:
>    lib /def:libfftw3-3.def /MACHINE:X64
>    lib /def:libfftw3f-3.def /MACHINE:X64
>    lib /def:libfftw3l-3.def /MACHINE:X64
>    Until now, the FFTW should be correctly install for pip
> 6. Run "pip install pyfftw". If there are __imp_* symbol problems, run step 5 again and then run step 6.
> 7. move the following files to Anaconda3\Lib\site-packages\pyfftw
>    libfftw3-3.dll,  libfftw3f-3.dll,    libfftw3l-3.dll
> 8. Happy using Pyfftw!
> 
> [After notes] The main problem is that pip install does not recognise many things (like some VC headers, FFTW libraries), and I don't know why. The above steps are rather lengthy but it works well and is tested many times (thanks to multiple machines I am using). I hope this post can somehow help.
When I run "lib /def:libfftw3-3.def /MACHINE:X64
" I get this error: 'lib' is not recognized as an internal or external command,
can you help me?

**Comment by hgomersall** [comment]
I still don't quite understand why you need to build your own windows builds. There are live builds pushed against every merge in bintray. Am I missing something?

**Comment by saharsalimpour** [comment]
I want to run Stockwell transform from this site (
https://github.com/claudiodsf/stockwell  ) so I have to install FFTW in my
windows10. I installed visual studio 2019 and do step 2 and 3 according to
( https://github.com/pyFFTW/pyFFTW/issues/73#issuecomment-516786512  ), but
when I write  lib /def:libfftw3-3.def /MACHINE:X64 , I get error.
Could you help me?

**Comment by hgomersall** [comment]
Oh, so this has nothing to do with install pyfftw, but to do with getting Windows to recognise the FFTW libs? You're well outside my knowledge area here. I try to avoid building stuff on windows because it always seems painful. Are you in the command line interface for using the visual studio tools? (not just the a default `cmd`). There might be some script you need to run to set up the path properly. Windows is a real hassle, how about using a virtual machine?

**Comment by saharsalimpour** [comment]
But at this time I have to use Windows. As I understand FFTW doesn't work
in Windows, does it?

**Comment by saharsalimpour** [comment]
I use the developer command prompt.

**Comment by hgomersall** [comment]
Yes, it absolutely works, but I'm not the author of FFTW, just the python bindings (along with other people). I suggest going to ask the authors of the Stockwell transform, or the authors of FFTW, or someone that understands building stuff on Windows (I am not that person).

**Comment by saharsalimpour** [comment]
Ok thanks a lot

**Comment by grlee77** [comment]
< I get this error: 'lib' is not recognized as an internal or external command,

This sounds like you are in a regular command prompt and not the visual studio command prompt (this is not your usual windows command prompt, but one that has added various visual studio-related things to the path). You need to be in that one so the compiler and tools like `lib` will be on your path.

If you are willing to use `conda` there are Windows packages for both `fftw` and `pyfftw` available via the `conda-forge` channel, although these currently do not offer the `long double` precision variant. (I think the limitation with `long double` was trying to support old visual studio for Python 2.7. I think conda-forge is dropping 2.7 going forward, so that could perhaps be revisited soon).
