### ISSUE TITLE
Python 3.4 and WinPython

### ISSUE THREAD

**Issue by TrekkieByDay** [hgomersall/pyFFTW#74]
Hello. Could you please provide directions for building from source an executable for Python 3.4 via WinPython? 0.9.2 only seems compatible with up to 3.3x. Thank you!

**Comment by hgomersall** [comment]
I can do better than that! Go and grab the brand sparkly new development builds:
https://bintray.com/hgomersall/generic/PyFFTW-development-builds

**Comment by hgomersall** [comment]
I'm keen to know if it works ok for you. Please let me know!

**Comment by TrekkieByDay** [comment]
Thanks for your response! This is great news... been on our radar for several months, but it has just now come to a head. When we fet this downloaded (kind of a process for us), i will switch over, run my unit tests, and let u know how it goes. Thanks again... very happy news!

**Comment by TrekkieByDay** [comment]
Just making sure... there are no compiled exes here... just the dlls to create them right?

**Comment by hgomersall** [comment]
Uhm... I don't understand. The .whl files you find on the above bintray link you should be able to install with something like: `pip install pyFFTW-0.10.0.dev0+4c652f3-cp35-none-win_amd64.whl`.

It should then just work.

**Comment by hgomersall** [comment]
That will include all the dlls you need (though they won't be installed for the system).

**Comment by TrekkieByDay** [comment]
Normally I jad installed via the WynPython external tools interface... pointing it to the PyFFTW .exe, which i believe is just a wrapper for the dlls. I jad never attempted to install a .whl as you suggest. However, i did attempt to do through the external tools interface... no joy yet. I will continue to fiddle with it. Thanks for ur help!

**Comment by hgomersall** [comment]
Just install pip and do it that way.

**Comment by TrekkieByDay** [comment]
So I did that, no problem with pip. I am getting an error though from ln 16 in the pyfftw init, the relative imprt, which traces down to ln 155 in init pyfftw.pyfftw.pxd. "ValueError: numpy.dtype has wrong size try recompiling." 

I am running on a 64 bit windows machine, and the .whl is cp34 win_amd64.

Plz excuse mispellings and shorthand... i have to tap the comments out on my smartphone unfortunately! :)

**Comment by hgomersall** [comment]
Hmmm, what version of Numpy are you using? I suspect you're using an older version than it is being built against.

**Comment by hgomersall** [comment]
Just to be clear, pyFFTW is built against Numpy 1.10.1. You should use this version of Numpy or later.

**Comment by TrekkieByDay** [comment]
Oh wow... the version of numpy included in the latest version of WinPython i am using is 1.9.3... looks like I will have to manually install the latest Numpy then? This is not ideal since I am using the latest WinPython. We were hoping to track our version against WinPython rather than against multiple sub packages. I will try installing the new numpy and get back to you. Thanks!

**Comment by hgomersall** [comment]
Yeah, it builds using the latest Conda with the default latest numpy. Perhaps it ought not to. hmmm...

**Comment by hgomersall** [comment]
I've just pushed a revision that uses 1.9.2. If you wait a couple of hours, that should be pushed up to bintray (assuming the tests complete fine). Check out: https://ci.appveyor.com/project/hgomersall/pyfftw

**Comment by TrekkieByDay** [comment]
Sweet! I just checked the progress... looks like 3.3 32 bit failed... and 3.5 32 bit failed... but 3.4 is good to go! :D

**Comment by TrekkieByDay** [comment]
Does the whole series have to pass befire push to bintray or do individual versions that pass get pushed?

**Comment by hgomersall** [comment]
Nope, they're pushed individually, so they should be there. It was a silly failure to do with contention on the CI system so can be safely ignored.

**Comment by hgomersall** [comment]
oh, it seems 32 bit for 3.5 is also broken (it actually doesn't like 1.9.2).

**Comment by TrekkieByDay** [comment]
Alas. :( So where does fit in ur plans? Are u gonna make a separate 1.9.2 permutation or will there jist be one to handle both?

**Comment by hgomersall** [comment]
I'll probably make it dependent on the python version, so 1.9.2 for less than 3.5. Does it work now?

**Comment by TrekkieByDay** [comment]
Alas because of sec, i jave to go thru a process to dl it... i will have it soon tho and will let u know. Thank u again so much. Let me just say that I have been enjoying purging Matlab... ur software is a key reason we can do so.

**Comment by TrekkieByDay** [comment]
Okay so we were able to get version 3.4 at 64 bit to work just fine. However, there seems to be some mistakes in the updated 3.3 64-bit version. Specifically there are function calls made in _utils.py that do not exist, e.g. is_byte_alligned and empty_alligned.  I have not tested the 3.5 version.

**Comment by hgomersall** [comment]
It's the same code. I'm not sure how that can make sense. The tests are completing fine.

What are you doing to trigger an error?

**Comment by TrekkieByDay** [comment]
So actually this is my fault, due to mistakenly swapping path. Was my mistake. I am trying to incorporate pyfftw in my app directly... and have a switch import depending on the python version number being run. All looks good on ir end, srry for the re herring

**Comment by TrekkieByDay** [comment]
Alrighty, I came in this morning and fixed all my issues. They all, as usual, came down to pretty obvious errors i was stupidly making. :)  Quick question: do u make the C source files available in the case we wish to compile the dlls from scratch? I ask because there may be a time in the future when we want to move to a new Python version before you have made it available. Thanks again for bearing with me. And thanks again for ur help (and for making this tool available!)

**Comment by hgomersall** [comment]
The C source files are compiled from the cython files (the .pyx and .pxd files). You can just install Cython to generate them.

**Comment by hgomersall** [comment]
Or do you mean FFTW? That comes from the FFTW developers: www.fftw.org

**Comment by TrekkieByDay** [comment]
I was confused about the C source files... but now Im good. I am a new Python programmer and was expecting some .c or .cpp files... did not realize the Cython layer (I only have vague awareness of Cython at the moment but will be learning it as we optimize our app for speed). I was aware that your app is a wrapper for FFTW (which we also use in C directly on another project). 

FYI, I have run your new version, both 3.3 and 3.4 64 bit, and all my unit tests are passing. So if that is useful to u, the update has not broken anything on our end!

Thanks again for being patient. This conversation helped a lot of people on our team. :)

**Comment by hgomersall** [comment]
Pleased I can help. Thanks for the useful update re nothing broken - I'd have been surprised (and a bit frustrated!) if it had broken anything.

Just a quick FYI - the new builds are using Numpy 1.9 across all versions. I'll stick with this for a while.
