### ISSUE TITLE
Release GIL during planning?

### ISSUE THREAD

**Issue by zpincus** [hgomersall/pyFFTW#75]
Currently, while calling into FFTW to create a plan, pyFFTW holds onto the GIL. So it's not possible to have a second python thread executing while FFTW does its planning. (Use case: I want to log a warning if planning takes more than 5 seconds or whatever, so that I know if something went wonky with my saved wisdom file. Thus, firing off a timer in another thread seems like the thing to do, except for the GIL not being released by pyFFTW, which means my second python thread doesn't run until the planning is done.)

Would adding `with nogil:` around [pyfftw.pyx:1086](https://github.com/hgomersall/pyFFTW/blob/master/pyfftw/pyfftw.pyx#L1086)
be a safe and sane change? Alternately the plan functions could be declared [nogil](http://docs.cython.org/src/userguide/external_C_code.html#declaring-a-function-as-callable-without-the-gil).

This is not unrelated to issue #13, for that matter. There are reasonable use-cases where one would want to release the GIL during single-threaded FFTW execution so as to run something else in a different python thread concurrently. Is there any reason the code refuses to release the GIL during single-threaded FFTW execution? 

As an aside, the [documentation](https://hgomersall.github.io/pyFFTW/pyfftw/pyfftw.html) states that "If the number of threads is greater than 1, then the GIL is released by necessity". I'm not sure this is actually the case, and this may indicate some misconceptions about the GIL. C code that spins up its own threads would still work fine if the GIL is held, unless those threads need to interact with the python interpreter in any way (such as calling python callbacks). For FFTW this seems to not be the case, right?

The reason to release the GIL doesn't have to do with whether or not the called code is multithreaded -- releasing the GIL is strictly a nicety to allow other python threads to run whilst *any* C code executes  (single- or multi-threaded). Otherwise one python thread's long-running call into C will block *all* python threads. So, unless I am rather mistaken (a distinct possibility!), the number of threads FFTW is going to use should have nothing to do with whether pyFFTW should release the GIL before calling into FFTW... 

Put another way, I don't see any reason why every FFTW function that does non-trivial computation shouldn't be declared `nogil` in the cython files. Or at lease all functions that don't need python callbacks (if there are any that do). Am I missing something? Happy to get a PR together if it would help.

Thanks!

**Comment by hgomersall** [comment]
Yeah, very good point, so thanks.

#13 is an implicit recognition of the fact that the GIL handling is not quite right. I agree with you that it should be released prior to calls into an FFTW execution, and I'd be very pleased if you could put together a PR. I think it would be pretty simple, I just haven't had the impetus yet to sort it.

The potential issue with nogil being around the planning stage is that the planner is [not thread safe](http://www.fftw.org/doc/Thread-safety.html). This means that a user could try to create to FFTW objects from different threads at the same time, which the GIL protects against. Now, I'm of the opinion that probably this is a misuse of the GIL and it's up to users to make sure they don't break things when foraying into multithreaded programming, in which case the correct thing is to release the GIL and document the lack of thread safety. Your use case is compelling enough to justify it (previously I hadn't considered all the implication of locking the interpreter during planning).

One subtlety is that interfaces functions would then not be thread safe, though this can be remedied with a lock around the planning stage.

What do you think? Again, keen for a PR when sorted (separate if possible to the other one) for this. :)

**Comment by zpincus** [comment]
Thanks! I hadn't realized about the issue of thread-safety in planning.

How about two different PRs:
1. remove the GIL around fftw_execute even in the single-threaded case (for #13)
2. remove the GIL around the planning call, and instead replace it with a pyFFTW-level lock. This way there's no way that planning can get called simultaneously by multiple threads (and then the interfaces will work safely too), but any non-FFTW python threads can still get time-slices while planning is ongoing. 

Does this sound like the right approach?

**Comment by hgomersall** [comment]
I think so. I don't think  we need any additional tests for this. It's hard to see what those tests would look like, so just the modified code that satisfies the current test suite would be great.

**Comment by zpincus** [comment]
Oh huh, there are already `nogil` annotations to the FFTW execute function prototypes in `pyfftw.pxd`, as well as the `fftw_generic_execute` function pointer type. So it turns out that the GIL is already released for even single-threaded FFTW execution (as functions annotated with `nogil` in cython are executed without the GIL even in the absence of a `with nogil:` block). I tested this on my machine and it is definitely the case that python threads can continue during execution of a single or multi-threaded FFTW execution.

So I'll do a PR that removes the unnecessary `with nogil` from the FFTW execution, and a separate one that adds `nogil` and a python lock around planning.

Quick question: what's the best way to run the full test suite? Traivs runs `setup.py test` but the docs for setup say that's only an abbreviated test.

**Comment by hgomersall** [comment]
Oh, so they are (whoops!). Yes, simply removing the unnecessary branch based on the number of threads and the nogil would be sufficient. It would be great if you could include the docs in the PR as well.

`setup.py test` _should_ run the full test suite; the abbreviated tests are with `setup.py quick_test`. The former does a `python -m unittest discover` (where the python executable is looked up from the running python instance). Which docs about setup.py are you referring to?

**Comment by zpincus** [comment]
OK, see PR #77 for removing the nogil block. Tests pass on py 2.7 and 3.4 on my machine at least.

A PR for the planning case will be coming shortly.

Regarding the test suite, I realize that I had mixed up `setup.py test` and `quick_test` when skimming through that file. The latter notes that it's not an exhaustive test, and I somehow thought it applied to the former.
