### ISSUE TITLE
Conda downloads are failing

### ISSUE THREAD

**Issue by caspervdw** [hgomersall/pyFFTW#76]
Travis is erroring on the PyFFTW download from anaconda:

    Error: MD5 sums mismatch for download: https://conda.anaconda.org/soft-matter/linux-64/pyfftw-0.9.2-np18py27_0.tar.bz2 (2898a378840ba43e6d120ce8cf3ec2e5 != 7f6b58a784abaa4df41e886637e6ebd5)

    Error: MD5 sums mismatch for download: https://conda.anaconda.org/soft-matter/linux-64/pyfftw-0.9.2-np19py34_0.tar.bz2 (2898a378840ba43e6d120ce8cf3ec2e5 != 83ce15739d67b01343e1ce3f6213f0b2)

Only on np18py27 and np19py34, others are fine. See https://github.com/soft-matter/trackpy/issues/339

**Comment by hgomersall** [comment]
Is this not a problem for soft-matter? (or have I misunderstood something?)

**Comment by hgomersall** [comment]
To be clear, I have nothing to do with any anaconda repositories for pyFFTW. I'm (slowly) getting this sort of thing sorted, but it's not quite there yet.

**Comment by caspervdw** [comment]
Sorry, my mistake, this indeed appears to be an issue with the soft-matter channel. Thanks for pointing it out!

**Comment by hgomersall** [comment]
no probs!
